#!/usr/bin/env bash
clear
echo "*** MEU GIT ***"
echo
echo "(1)git status"
echo "(2)git add *"
echo
echo "Opção: "
read menu

if [[ $menu == 1 ]]; then
    clear
    echo "git status selecionado!"
    echo
    git status
    echo
    echo "<Tecle qualquer tecla para sair>"
    read
fi

if [[ $menu == 2 ]]; then
    clear
    echo "git add * selecionado!"
    echo
    git add *
    echo
    echo "<Tecle qualquer tecla para sair>"
    read
fi
